### ISSUE TITLE
Send photos with TelegramBot

### ISSUE THREAD

**Issue by GabrieleAnsaldo** [magnitopic/YouTubeCode#2]
Hello,
I just saw your video on Youtube and I tried the code for the TelegramBot.  It works like a charm, thank you so much for that. However, my question is regarding sending a png photo as a text. 

For example, imagine a write on the telegram chat -->"Photo"

The bot should send me a photo placed in a specific directory on my computer (where I am running the python file)

I hope my explanation makes sense.
If so, how do I change the code to do that task?

Thanks in advance!!

**Comment by magnitopic** [comment]
Hey!!

Sorry for the late reply, just saw this today.

I did some Googling to your question and this should do it.

`elif 'Hi' in text:
reply(img=urllib2.urlopen('img url').read())`

Sorce: [](https://stackoverflow.com/questions/31860628/how-to-send-an-image-from-a-telegram-bot/32441772)

Best regards.
